# Generated by Django 6.0.4 on 2026-04-19 03:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_add_vector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFtsSingleLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "fts_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="vector for full-text search",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentFtsWithoutLoop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iso_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("it", "Italian"),
                            ("xx", "Other"),
                        ],
                        default="xx",
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "fts_vector",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                iso_language="en",
                                then=django.contrib.postgres.search.SearchVector("title", config="english", weight="A"),
                            ),
                            models.When(
                                iso_language="fr",
                                then=django.contrib.postgres.search.SearchVector("title", config="french", weight="A"),
                            ),
                            models.When(
                                iso_language="de",
                                then=django.contrib.postgres.search.SearchVector("title", config="german", weight="A"),
                            ),
                            models.When(
                                iso_language="it",
                                then=django.contrib.postgres.search.SearchVector("title", config="italian", weight="A"),
                            ),
                            default=django.contrib.postgres.search.SearchVector("title", config="simple", weight="A"),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                        verbose_name="vector for full-text search",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentWithSingleFtsField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iso_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("it", "Italian"),
                            ("xx", "Other"),
                        ],
                        default="xx",
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "fts_vector",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                iso_language="en",
                                then=django.contrib.postgres.search.SearchVector("title", config="english", weight="A"),
                            ),
                            models.When(
                                iso_language="fr",
                                then=django.contrib.postgres.search.SearchVector("title", config="french", weight="A"),
                            ),
                            models.When(
                                iso_language="de",
                                then=django.contrib.postgres.search.SearchVector("title", config="german", weight="A"),
                            ),
                            models.When(
                                iso_language="it",
                                then=django.contrib.postgres.search.SearchVector("title", config="italian", weight="A"),
                            ),
                            models.When(
                                iso_language="xx",
                                then=django.contrib.postgres.search.SearchVector("title", config="simple", weight="A"),
                            ),
                            default=django.contrib.postgres.search.SearchVector("title", config="simple", weight="A"),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                        verbose_name="vector for full-text search",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iso_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("it", "Italian"),
                            ("xx", "Other"),
                        ],
                        default="xx",
                        max_length=2,
                        verbose_name="ISO language",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "fts_vector",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                iso_language="en",
                                then=django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.SearchVector("title", config="english", weight="A"),
                                    "||",
                                    django.contrib.postgres.search.SearchVector(
                                        "content", config="english", weight="B"
                                    ),
                                    django.contrib.postgres.search.SearchConfig("english"),
                                ),
                            ),
                            models.When(
                                iso_language="fr",
                                then=django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.SearchVector("title", config="french", weight="A"),
                                    "||",
                                    django.contrib.postgres.search.SearchVector("content", config="french", weight="B"),
                                    django.contrib.postgres.search.SearchConfig("french"),
                                ),
                            ),
                            models.When(
                                iso_language="de",
                                then=django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.SearchVector("title", config="german", weight="A"),
                                    "||",
                                    django.contrib.postgres.search.SearchVector("content", config="german", weight="B"),
                                    django.contrib.postgres.search.SearchConfig("german"),
                                ),
                            ),
                            models.When(
                                iso_language="it",
                                then=django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.SearchVector("title", config="italian", weight="A"),
                                    "||",
                                    django.contrib.postgres.search.SearchVector(
                                        "content", config="italian", weight="B"
                                    ),
                                    django.contrib.postgres.search.SearchConfig("italian"),
                                ),
                            ),
                            models.When(
                                iso_language="xx",
                                then=django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.SearchVector("title", config="simple", weight="A"),
                                    "||",
                                    django.contrib.postgres.search.SearchVector("content", config="simple", weight="B"),
                                    django.contrib.postgres.search.SearchConfig("simple"),
                                ),
                            ),
                            default=django.contrib.postgres.search.CombinedSearchVector(
                                django.contrib.postgres.search.SearchVector("title", config="simple", weight="A"),
                                "||",
                                django.contrib.postgres.search.SearchVector("content", config="simple", weight="B"),
                                django.contrib.postgres.search.SearchConfig("simple"),
                            ),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                        verbose_name="vector for full-text search",
                    ),
                ),
                (
                    "semantic_vector",
                    pgvector.django.vector.VectorField(
                        default=None,
                        dimensions=768,
                        editable=False,
                        null=True,
                        verbose_name="vector for semantic search",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["fts_vector"], name="core_document_fts_vector_idx"
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["semantic_vector"],
                        m=16,
                        name="core_document_distance_idx",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
            },
        ),
    ]
